CREATE TABLE IF NOT EXISTS hero_content (
  id INT AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(255) NOT NULL DEFAULT '',
  title VARCHAR(255) NOT NULL DEFAULT '',
  title_highlight VARCHAR(255) NOT NULL DEFAULT '',
  subtitle TEXT,
  body TEXT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS hero_slides (
  id INT AUTO_INCREMENT PRIMARY KEY,
  image_url VARCHAR(500) NOT NULL,
  alt_text VARCHAR(255) DEFAULT '',
  label VARCHAR(255) NOT NULL DEFAULT '',
  title VARCHAR(255) NOT NULL DEFAULT '',
  title_highlight VARCHAR(255) NOT NULL DEFAULT '',
  subtitle TEXT,
  body TEXT,
  text_position VARCHAR(40) NOT NULL DEFAULT 'center',
  label_color VARCHAR(20) NOT NULL DEFAULT '#FDE68A',
  title_color VARCHAR(20) NOT NULL DEFAULT '#FFFFFF',
  title_highlight_color VARCHAR(20) NOT NULL DEFAULT '',
  subtitle_color VARCHAR(20) NOT NULL DEFAULT '#F5F5F5',
  body_color VARCHAR(20) NOT NULL DEFAULT '#E5E5E5',
  sort_order INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
