CREATE TABLE IF NOT EXISTS hero_buttons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  slide_id INT NULL,
  label VARCHAR(120) NOT NULL,
  url VARCHAR(500) NOT NULL,
  style VARCHAR(40) DEFAULT 'primary',
  sort_order INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  open_in_new_tab TINYINT(1) DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
